[package]
name = "netherite-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0"
netherite-macros.path = "../macros"