[package]
name = "netherite-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive", "unstable"] }
serde_json = "1"
bytes = "1"
netherite-macros.path = "../macros"